## **News Story**

**Dupont Underground: Advocacy Through Art in an Abandoned Metro Station**

In a tunnel beneath one of Washington D.C.'s most culturally profound community circles, Dupont Underground has been a unique space to showcase art in The District. This abandoned subway station may not take its visitors to a physical location, but its linear path in displaying art takes one through a less bumpy, metaphorical artistic journey.  

From drag shows to art exhibits to short film screenings, Dupont Underground has a wide array of choices to display art. This not only makes the organization what it is but assists in transforming the cultural identity in Washington D.C. through art.

Ana Harvey is the CEO of Dupont Underground and has been there for a year and a half. What makes Dupont Underground special to her is its flexibility and how unusual it is.

"It really allows us to highlight art that is probably more difficult to fit somewhere else," said Harvey. 

She says that their goal is to create a platform for new talent and up-and-coming artists who need spaces to display their art. Dupont Underground is this space and this is their mission. 

In March, they held an exhibit called "An Observation of the Resistance, Resilience, and Joy of the Black Woman." Harvey said that the artist was never a curator but came to Dupont Underground and expressed interest in curating. 

"I said this is a place to curate and she curated. That made us really happy."

Dupont Underground encourages artists to reach new heights and expand their vision.

```         
Blake Johnson is the program manager and has been at Dupont Underground since December.
```

What attracted Johnson to Dupont Underground is that the staff really embraces the space. "I appreciate that we don't try to hide what this space is and that we try to work with it rather than against it." 

There are a variety of artists who they collaborate with. This ranges from working with an embassy for one month and then an individual artist the next month. Since there are myriad ways to make use of the space, it makes the experience all the more exciting.

Lucrecia Laudi is the Vice Chair and one of the co-founders of Dupont Underground. She helped discover it about 15 years ago. She said that Dupont Underground became open to the public in 2016. 

```         
Laudi highlighted the location of Dupont Underground, saying that it is well-connected to all of The District.
```

"This is something very important to us because we can be accessible to everyone. This is sustainable development because we are really repurposing an existing infrastructure that's totally abandoned and closed," said Laudi. 

They work for the people. Since this is done in a public space, Laudi said that they do not want commercial development there. 

"We are a cultural platform. We are interdisciplinary," said Laudi. Giving exposure to individuals of different artistic backgrounds is an important part of their core mission. 

```         
Dupont Underground engages in collaborations and partnerships with all different cultures and types of art. This in turn attracts people with distinct interests. They bring in diversity through expression and exhibiting artists with different backgrounds. There are a lot of young people who visit, but there are also middle-aged and older people who go as well.
```

"At our last drag show, there was a guy that got pulled on stage that was 55. It was awesome. He was so sweaty when he left. He was amazing," said Johnson. 

```         
Being in Washington D.C. also enables them to consider how they can convey all of the diversity and identity that pulses throughout the city. This is why they present international perspectives. It\'s because people from all over the world live in the nation\'s capital.
```

"27,000 people come every year," said Harvey.

```         
They also offer the space free for nonprofit organizations. \"It's a huge space so as long as we don't have to spend money, you don't have to spend money,\" said Harvey. It is something she said they are very proud of.
```

"The way that we are able to do things on an international level and a local level literally could only happen in Washington D.C. and that's I think one of my favorite things about this space," said Johnson. 

Dupont Underground gives people the opportunity to do something special. With Laudi's favorite exhibitions being those in architecture, Johnson's favorite was "The Cost of Living: An Observation of the Resistance, Resilience and Joy of the Black Woman." Harvey's favorite exhibit was "The Gender Within: The Art of Identity Exhibition."

One of the reasons that Johnson wanted the job was because of the "The Gender Within" exhibit.  This exhibit was an open call to trans-artists from the area. Some of these artists have never had their work on display before, which excited Johnson. 

Another significant exhibit for Harvey was "BLACK X." This was a video exhibit about mental health among African American males. 

They are going to start a series called "Patient Advocacy Through Arts," which they will be doing once a year. 

```         
Most of the artists come to Dupont Underground themselves to have their art shown. \"We must get one or two a week,\" said Harvey.
```

Abbas Shobeiri, artist and physician, started presenting his art exhibition "Do You See Me!Paintings of Postpartum Trauma and Healing" at Dupont Underground for the May exhibition. 

Shobeiri is the head of the gynecology program at Inova Health. "My practice is dedicated to women, specifically to patients with postpartum issues. So, that's what I do. The exhibit that you see is a linear story of grief and resolution and recovery that starts from shock to resolution."

```         
The space was ideal for Shobeiri because the tunnel would allow him to carry the linear story. He said that other exhibits of space that he looked at did not have this kind of configuration.

His exhibit showed paintings that were the result of a 30-year process of him listening to patients. Childbirth is usually viewed as a positive experience, but that is not always the case. When Shobeiri finished medical school and started hearing about the traumatic experiences of different women from childbirth, he realized that it is not always a happy experience.

It took Shobeiri 15-20 years to construct the exhibit. There are statements aligned with each stage of postpartum trauma in his display of paintings. Many of the patients who visit look at the statements and deeply resonate with them.

Whenever a patient made a statement to Shobeiri regarding postpartum trauma, he said that \"it literally gets stuck in your soul.\"

He feels obligated to share these sentiments and statements to establish community with those continuing to heal from postpartum trauma. \"You need to do something with it because then it\'s a burden. Now you are a story keeper.\"

By painting these sentiments, he said that he is lighting his own burden while bringing advocacy to the issue. Dupont Underground has allowed Shobeiri to do so.
```

 "I really like the space because if you look at my paintings, the way that I paint is very raw and I didn't want it to literally be in a place that doesn't have any character. Dupont Underground definitely has a lot of character," said Shobeiri. 

```         
The space and location of Dupont Underground are key for artists like Shobeiri to bring awareness to an issue.

These kinds of artists continue to use Dupont Underground to expand their ideas, hopefully allowing their exhibits to gain traction and popularity.
```

"It functions like a partnership. Once we're actually in it with the artists, it's very much like we're working with these artists. Usually, the first approach is, 'I am an artist. I would like to display my pieces," said Johnson. 

"We Look for content. It's not just, 'I wanna show my flowers," said Laudi. 

```         
In terms of future plans, Dupont Underground staff is working to upgrade the electrical system. They will also be installing a system for water which entails putting in bathrooms and sprinkler systems.
```

"We're gonna have a functioning place," said Harvey.

```         
They are also now ADA-accessible. They are improving the standards of the building in numerous ways, but want the general essence of the tunnel to remain the same. \"We don't wanna ruin the nature of it, but we wanna make sure it's a good place to visit,\" said Harvey.
```

In addition, Harvey said they have been getting requests for galas and parties, but do not want to take up these offers until the building is at the standard it needs to be at.

"We're just creating a slightly more hospitable environment," said Johnson.

Private events will bring in more funds for them, as they now only have \$5000, said  Harvey. 

```         
This will inevitably allow them to continue to do what they love to do: serve as a platform for creativity.
```

"I'm really excited about how programming is going to evolve and how more people from different walks of life will find us," said Harvey. 

```         
Attracting local populations is also important, so they won\'t forget that they are in Washington D.C, said Laudi.

Laudi recognizes that they still need support and have a lot of work to do, especially with the impending construction on Dupont Circle starting Fall of 2023.
```

"They're gonna have to get into our tunnels, so we're gonna be affected in terms of noise and people," said Harvey.

```         
Harvey is fearful of what will be happening on the surface. The street is going to be closed, there will be traffic and nowhere to park. \"People may not want to come here,\" said Harvey.
```

This will be an issue that they have to deal with for two years and will have to find creative ways to navigate. 

"It's going to be our challenge. We know how to engage. Our entry is not going to be affected," said Laudi. 

```         
Dupont Underground will overcome this obstacle to ensure that art, advocacy and culture continue to be dispersed in the Washington D.C. community. It\'s a matter for them to make it known that they are still alive and open. It\'s a matter for them to continue this upward trajectory, engaging people from all walks of life through art.
```

\
[Back to home page](https://lizzycruz.github.io/MyWebsite-/#communicationbusinessjournalism) \
