---

---

## **Paper at GW:**

##### The paper below is a reflection I wrote on my Small Group Communication class. In this class, I worked with two different small groups on two different projects. The paper consists of reflecting on different concepts learned in class and how these concepts were potentially utilized in the group projects that I was working on. I also compared both group projects and looked back on how I progressed as a group member and student.

**Small Group Communication Reflection**

```         
Small Group Communication has enabled me to see working in groups differently, providing useful insight into how to best succeed in a group. I learned about how to best work through challenges that come with working in a group and how to navigate group differences. Putting these skills to use with the two group projects in this class enhanced my collaboration abilities and helped me work more efficiently and effectively in a group.

Since working in groups was a main component of this class, it was interesting to note the different modes of communication used by various group members and classmates. Learning how to adapt and communicate to different people was an important part of success within a given task during a group conversation or class activity. A study online called \"Enhancing Small Group Communication in the Language Classroom. The Modern Language Journal '' evaluates the impact of a training program that implements cooperative strategy, focusing on the patterns of interaction that transpired while small groups completed an oral discussion. The assumption was said to be that students can be taught to interact with each other in a manner that would spark the creation of opportunities for growth and learning (Naughton, 2006). This is reminiscent of a discussion in class of what the benefits of working in groups are and how they foster creativity while allowing for different creative ways to problem solve. I think cooperative learning is an important factor of group work in allowing students to work together towards a common goal. This was seen during the third quiz because we did it as a group. We all worked together to generate good answers that resulted in a good grade on the quiz by collaborating, listening, and helping each other.

The **rules** and **norms** of a group set the general foundation and standard for how the group is expected to operate. Group Norms are \"informal, implicit standards of behavior and procedures by which members operate, and group rules are \" formal, explicit standards of behavior and procedures by which a group operates\" (Adams et al., 2021). Rules and norms help a group function well and stay organized. During the second group project, many group norms and rules came into play when writing the group contract. This was more so establishing the rules, with the written out document, but would soon translate into norms as the group practiced them more. For the second project, my group contract consisted of what typical group rules might entail. This includes: being responsive to texts within at least 24 hours, communicating if there were any time conflicts, being respectful, and making sure members were doing their respective work for the project. For the group projects in this class, group norms primarily developed **explicitly** and **culturally** (Adams et al., 2021). Explicit norms are developed through \"explicit statements\" by a leader or group member (Adams et al., 2021).This was seen while making the group contracts and having conversations about what general expectations of the group would be. Norms were developed culturally because all of us live in the general culture of GW. With that, since all of us are GW students who have done group work before, we understand how these projects function and what they may consist of. In addition, GW students tend to be very driven with their school work, allowing for a norm to be established with a group of students who expect to succeed and do well in their classes. In both of my groups for project #1 and #2, there were no deviants. Deviants are \"members who consistently violate group norms\" (Adams et al., 2021). In my experiences working in these groups, I got the general sense that each member wanted to move along with the project, therefore there was no slacking with norms within the group. This may have been a detriment with the first project, which was finding ways to promote Communication as a second major. Since we had a bigger group, it was harder to hone in on the issue and refocus our communication. This was because we were focusing more on making sure everyone had something to work on and that everything was done in time.
```

During the first project, we were not clear in promoting the major in communication as effectively as we could, and groupthink could have played a part in this. The communication club was more of a focus for this project than it should have been. If someone had spoken up to switch gears and reevaluate, we could have had better feedback from the project. Ways that we learned to **prevent groupthink** include: "kicking the problem around, establishing norms of critical evaluation, preventing leaders from stating their preferences at the beginning of a group's decision-making or problem-solving session, and preventing insulation" (Adams et al., 2021). I have always been aware of what groupthink is and because of this I expected not to succumb to it. It is interesting reflecting back and realizing how many of us are susceptible without being aware of it. It shows how easy it is to follow the idea of a group when involved, because if a majority of the group agrees on a particular way to do something, it is easier to believe that it is correct. This especially felt true with the larger group I was in. A study called "The impact of group size and social presence on small-group communication: Does computer-mediated communication make a difference?" posed interesting questions and concluding results that are pertinent to this topic. In this study, "key communication factors (appropriateness, openness, richness, discussion quality, and accuracy) were compared for three different treatments (proximate without CMC support, proximate with CMC support, and virtual with CMC support)" (Lowry et al., 2006). Conclusions showed that FtF communication with CMC support yielded better communication outcomes than virtual communication with CMC support  (Lowry et al., 2006). This is understandable and something I agree with when doing group work, because I find face to face communication to be easier to communicate and complete work more efficiently. CMC in use with face to face communication is favorable as well. This was seen because during my second project with meetings when we could only facetime. If everyone's camera was on, we would still be productive. It was only more of a problem if everyone's camera was off or if we were not able to call or facetime at all, and had to resort to texting to communicate. Text made it more difficult because of not everyone being on their phones at the same time, therefore prompt messages could not be transmitted. 

```         
For both group projects and with the group quiz as well, I found that the more I participated and had my ideas accepted and used, the more I wished to collaborate and engage myself. When a group constantly rejects one\'s ideas or leaders take charge without asking for the input of others, it can result in isolation from the group. A study called \"The Effects of Communication Motives, Interaction Involvement, and Loneliness on Satisfaction: A Model of Small Groups\" focused on how different communication motives impacted \"influenced, involvement, and  loneliness\" and how these factors influenced group satisfaction (Anderson & Martin, 1995). Results showed that pleasure was grounds for communicating in a responsive manner, while \"escape, control, and inclusion\" were not reasons to communicate responsibly (Anderson & Martin, 1995). In addition, there was a direct relationship between the need for satisfaction and affection, which calls for the need for more training, education, and understanding the different motives of group members for group tasks (Anderson & Martin, 1995). Using this study to reflect on my interpersonal needs during group work, I have realized that feeling valued is a critical part of feeling positively engaged in a group project. This includes having positive and helpful feedback from my group members and not being overlooked, as on many occasions, one or two leaders like to take charge and fail to consider the input of others. Luckily with my group projects and my group work I did not feel overlooked and felt free to participate and share my thoughts. I do recognize however, that I tend to be quiet in my classes as I naturally enjoy listening more than participating. As the semester progressed, I was better with my participation, but this is still something that I am looking to improve on and I am hoping to share my thoughts during class/group work on a more consistent basis. Being in a small group of only three people for the second project definitely allowed me to find confidence in my ideas more, pushing me to speak up and take action. 

This class has allowed me to learn how to become a better group member and navigate the difficulties of scheduling, communication, and time constraints that come with group work. I know what to prioritize in group projects and what habits to avoid to work towards a successful experience.I have grown as a student and individual, adapting worthwhile skills that will allow me to be successful when working in groups not only in my future career, but in the different facets of my life that form my identity.
```
